In [1]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])
print("Jumlah:", np.sum(x))
print("Rata-rata:", np.mean(x))
print("Maksimum:", np.max(x))
print("Minimum:", np.min(x))
print("Standar deviasi:", np.std(x))


Jumlah: 15
Rata-rata: 3.0
Maksimum: 5
Minimum: 1
Standar deviasi: 1.4142135623730951


In [2]:
arr = np.arange(1, 13).reshape(3, 4)
print("Array asli:\n", arr)

# Transpose
print("Transpose:\n", arr.T)

# Flatten
print("Flatten:", arr.flatten())

# Reshape
print("Reshape ke (4,3):\n", arr.reshape(4, 3))

# Slicing
print("Baris ke-1, kolom ke-2:", arr[0, 1])
print("Semua baris, kolom ke-3:", arr[:, 2])


Array asli:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Transpose:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshape ke (4,3):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Baris ke-1, kolom ke-2: 2
Semua baris, kolom ke-3: [ 3  7 11]


In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

print("Gabungan:", np.union1d(a, b))       # [1 2 3 4 5 6]
print("Irisan:", np.intersect1d(a, b))     # [3 4]
print("Selisih (a-b):", np.setdiff1d(a, b)) # [1 2]
print("Unik dalam a:", np.unique(a))       # [1 2 3 4]
