In [1]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Perkalian Elementwise (1*5, 2*6, 3*7, 4*8)
C_elemwise = A * B
print("1. Perkalian Elementwise:\n", C_elemwise)

# Perkalian Matriks (Matrix Product: Dot Product)
# (1*5 + 2*7), (1*6 + 2*8), dst.
C_matrix = np.dot(A, B)
print("\n2. Perkalian Matriks (np.dot):\n", C_matrix)

# Manipulasi: Transpose
A_trans = A.T
print("\n3. Transpose A:\n", A_trans)

1. Perkalian Elementwise:
 [[ 5 12]
 [21 32]]

2. Perkalian Matriks (np.dot):
 [[19 22]
 [43 50]]

3. Transpose A:
 [[1 3]
 [2 4]]


In [2]:
#contoh case sehari hari 'menghitung total pendapatan dari produk berdasarkan kuantitas dan harga satuan.'

import numpy as np

Q = np.array([5, 10, 8])         # Vektor Kuantitas
H = np.array([50000, 25000, 75000])  # Vektor Harga

# Biaya per produk: Perkalian Elementwise
Biaya_Per_Produk = Q * H
print("Biaya Per Produk (Elementwise):\n", Biaya_Per_Produk)

# Total Biaya Keseluruhan: Perkalian Skalar (Dot Product)
Total_Biaya = np.dot(Q, H)
print("\nTotal Biaya Keseluruhan (Dot Product): Rp", Total_Biaya)

Biaya Per Produk (Elementwise):
 [250000 250000 600000]

Total Biaya Keseluruhan (Dot Product): Rp 1100000


In [3]:
#array multidimensi

import numpy as np

# 1. Array 1 Dimensi (Vektor)
a_1d = np.array([1, 2, 3, 4])
print("1D Array Shape:", a_1d.shape) # (4,)

# 2. Array 2 Dimensi (Matriks 2x3)
a_2d = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print("\n2D Array Shape:", a_2d.shape) # (2, 3)

# 3. Array 3 Dimensi (Tensor 2x2x3)
a_3d = np.zeros((2, 2, 3))
print("\n3D Array Shape:", a_3d.shape) # (2, 2, 3)

# 4. Reshape (mengubah bentuk dari 2x3 menjadi 3x2)
a_reshaped = a_2d.reshape(3, 2)
print("\nArray Setelah Reshape (3x2):\n", a_reshaped)

1D Array Shape: (4,)

2D Array Shape: (2, 3)

3D Array Shape: (2, 2, 3)

Array Setelah Reshape (3x2):
 [[10 20]
 [30 40]
 [50 60]]


In [7]:
#contoh penerapan sehari-hari 'Data Cuaca Harian'
import numpy as np

# Array 3D: (Kota, Hari, Jam)
# 2 Kota, 3 Hari, 4 Jam pengukuran
Data_Suhu = np.zeros((2, 3, 4))
print("Shape Data Suhu:", Data_Suhu.shape)

# Contoh memasukkan data suhu rata-rata Kota 1 pada Hari 1 (indeks 0, 0)
Data_Suhu[0, 0, :] = [25, 27, 26, 28]

print("\nData Suhu Kota 1, Hari 1:\n", Data_Suhu[0, 0, :])

Shape Data Suhu: (2, 3, 4)

Data Suhu Kota 1, Hari 1:
 [25. 27. 26. 28.]


In [8]:
#slicing indexing
import numpy as np

A = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

# 1. Indexing Elemen Tunggal (Baris ke-3, Kolom ke-2)
# A[indeks_baris, indeks_kolom] -> A[2, 1]
elemen = A[2, 1]
print("Elemen A[2, 1]:", elemen) # Output: 100

# 2. Slicing Baris: Mengambil Seluruh Baris ke-2 (indeks 1)
baris_2 = A[1, :]
print("\nBaris ke-2 (A[1, :]):", baris_2) # Output: [50 60 70 80]

# 3. Slicing Kolom: Mengambil Seluruh Kolom ke-4 (indeks 3)
kolom_4 = A[:, 3]
print("\nKolom ke-4 (A[:, 3]):", kolom_4) # Output: [40 80 120]

# 4. Slicing Sub-matriks (Mengambil 2 baris pertama, 2 kolom terakhir)
sub_matriks = A[0:2, 2:4]
print("\nSub-matriks A[0:2, 2:4]:\n", sub_matriks)

Elemen A[2, 1]: 100

Baris ke-2 (A[1, :]): [50 60 70 80]

Kolom ke-4 (A[:, 3]): [ 40  80 120]

Sub-matriks A[0:2, 2:4]:
 [[30 40]
 [70 80]]


In [9]:
#contoh penerapan 'Analisis Nilai Siswa'
import numpy as np

# Matriks Nilai (Baris = Siswa, Kolom = [Tugas, UTS, UAS])
Nilai_Siswa = np.array([
    [85, 90, 75], # Siswa 1
    [70, 80, 85], # Siswa 2
    [95, 75, 90]  # Siswa 3
])

# Mengambil nilai UTS (Kolom ke-2, indeks 1) untuk SEMUA siswa
Nilai_UTS_Semua_Siswa = Nilai_Siswa[:, 1]
print("Nilai UTS Semua Siswa:", Nilai_UTS_Semua_Siswa)

# Mengambil SEMUA nilai (Tugas, UTS, UAS) untuk Siswa 3 (indeks 2)
Nilai_Siswa_3 = Nilai_Siswa[2, :]
print("\nNilai Lengkap Siswa 3:", Nilai_Siswa_3)

Nilai UTS Semua Siswa: [90 80 75]

Nilai Lengkap Siswa 3: [95 75 90]
